### ISSUE TITLE
Add a readme!

### ISSUE THREAD

**Issue by MartinSahlen** [mastoj/FatSlack#1]

**Comment by mastoj** [comment]
Lolol... it's coming.

**Comment by MartinSahlen** [comment]
Where is it??

**Comment by mastoj** [comment]
LOL :)... I've been doing a large rewrite to simplify it a little bit. I'll add a basic readme in a matter of minutes.

**Comment by mastoj** [comment]
First draft of readme added in https://github.com/mastoj/FatSlack/commit/bf47003a218d4bbb3fac672d8e6dd4a46c18a48b
